// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQJGWaasyVipGx7bONNK5Dz3JKv-TSNfo',
    appId: '1:643626760146:web:753fdf2f56852c97ab7a0b',
    messagingSenderId: '643626760146',
    projectId: 'plasma-hope-467112-t6',
    authDomain: 'plasma-hope-467112-t6.firebaseapp.com',
    storageBucket: 'plasma-hope-467112-t6.firebasestorage.app',
    measurementId: 'G-XTH6GLBG73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBcT8NbXt_CczBdYiiP7HLvUQSIRMfU3g',
    appId: '1:643626760146:android:f466ba0a46c0c9cdab7a0b',
    messagingSenderId: '643626760146',
    projectId: 'plasma-hope-467112-t6',
    storageBucket: 'plasma-hope-467112-t6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHWsJmZFN_dFABxa_gZ1YxQ3KDtT2exDI',
    appId: '1:643626760146:ios:793861067f45a064ab7a0b',
    messagingSenderId: '643626760146',
    projectId: 'plasma-hope-467112-t6',
    storageBucket: 'plasma-hope-467112-t6.firebasestorage.app',
    iosBundleId: 'com.example.projectKisan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCf6dH7mVumZfNZDaRtJCgTWpXDhDx5Ag',
    appId: '1:643626760146:ios:793861067f45a064ab7a0b',
    messagingSenderId: '643626760146',
    projectId: 'plasma-hope-467112-t6',
    storageBucket: 'plasma-hope-467112-t6.firebasestorage.app',
    iosBundleId: 'com.example.projectKisan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQJGWaasyVipGx7bONNK5Dz3JKv-TSNfo',
    appId: '1:643626760146:web:91a4ed8fc74b3109ab7a0b',
    messagingSenderId: '643626760146',
    projectId: 'plasma-hope-467112-t6',
    authDomain: 'plasma-hope-467112-t6.firebaseapp.com',
    storageBucket: 'plasma-hope-467112-t6.firebasestorage.app',
    measurementId: 'G-BQ3JBZ0X4P',
  );

}